#!/bin/csh

# -----------------------------------------
# Args list for Image Transfer Relay (FTN).
# -----------------------------------------

set DD    = @
set ID    = LOCAL_ITR
set PORT  = 6666
set KEY   = $ITR_CERTS/itr.private
set TRUST = $ITR_CERTS/server.public
set BASE  = $ITR_TMP
