#!/bin/csh

# --------------------------------------------------------------
# Config for: Log Archive Transfer (LAX): AG images
# --------------------------------------------------------------

# Logging info.
set LOG_ROLL            = TRUE
set LAX_LOG_MAX 	= 30000
set LAX_LOG_COUNT 	= 4

# Search pattern.
set PATTERN 		= "field_*_{successful,failed}.fits"

# Transfer Journal DB
set JOURNAL		= /occ/tmp/lax_lt.jdb

# Where the logs are.
set LOG_DIR		= /mnt/autoguider-image

# Routing information
set ROUTE		= lt_tmc_archive

# What to do with it after xfer.
set DISPOSAL		= DELETE_LATER

# How long after xfer to delete (sec).
set DELETE_AFTER	= 31400000 

# Where it goes.
set DEST_USER		= data
set DEST_HOST		= lt-qc.astro.livjm.ac.uk
set DEST_DIR		= /data/incoming
