#!/bin/csh

# ----------------------------------------
# Args list for Image Transfer Relay (LT).
# ----------------------------------------

set DD    = @
set ID    = LT_ITR
set PORT  = 6666
set KEY   = $ITR_CERTS/itr.private
set TRUST = $ITR_CERTS/server.public
set BASE  = $ITR_TMP
