#!/bin/csh

# --------------------------------------------------------------
# Config for: Log Archive Transfer (LAX): LT_MOPTOP1
# --------------------------------------------------------------

# Logging info.
set LOG_ROLL            = TRUE
set LAX_LOG_MAX 	= 30000
set LAX_LOG_COUNT 	= 4

# Search pattern.
set PATTERN 		= "*.gz"

# Transfer Journal DB
set JOURNAL		= /occ/tmp/lax_lt.jdb

# Where the logs are.
set LOG_DIR		= /mnt/moptop-image/1/log_archive/

# Routing information
set ROUTE		= lt_tmc_archive

# What to do with it after xfer.
set DISPOSAL		= DELETE_LATER

# How long after xfer to delete (sec).
set DELETE_AFTER	= 400

# Where it goes.
set DEST_USER		= eng
set DEST_HOST		= sdbserver
set DEST_DIR		= /sdb/LT/inst_logs/moptop
