#!/bin/csh

# --------------------------------------------------------------
# Config for: Log Archive Transfer (LAX): LT_RCS
# --------------------------------------------------------------

# Logging info.
set LOG_ROLL            = TRUE
set LAX_LOG_MAX 	= 30000
set LAX_LOG_COUNT 	= 4

# Search pattern.
set PATTERN 		= "Ops*rcs*.gz"

# Transfer Journal DB
set JOURNAL		= /occ/tmp/lax_lt.jdb

# Where the logs are.
set LOG_DIR		= /occ/logs/archive

# Routing information
set ROUTE		= lt_tmc_archive

# What to do with it after xfer.
set DISPOSAL		= DELETE_NOW

# Where it goes.
set DEST_USER		= eng
set DEST_HOST		= sdbserver
set DEST_DIR		= /sdb/LT/rcs_logs
