#!/bin/csh

# -----------------------------------
# Setup for: Archive Transfer Client.
# -----------------------------------

setenv ARCHIVE_HOME    $DEPLOY_HOME/itr
setenv ARCHIVE_SCRIPTS ${ARCHIVE_HOME}/scripts
setenv ARCHIVE_CERTS   ${ARCHIVE_HOME}/certs
