#!/bin/csh

foreach file (/mnt/rat-image/c_e*.fits)

    echo "Found $file "

    cat /occ/tmp/archive_info | grep $file

    if ($status == 0) then
	echo "$file is copied OK"

	/bin/rm -f $file

	echo "Removed $file"

    else
	echo " $file was not transferred"
    endif
end
 
