#!/bin/sh

# -------------------------------------------------
# Init launcher for: Data Generator Watchdog (DGW).
# -------------------------------------------------

. /occ/etc/deploy-bashrc

if [ $# -ne 2 ]; then   
    target=$DEPLOY_SYSTEM
else
    target=$2
fi

# Source function library.
/etc/rc.d/init.d/functions

DAT=`date -u +"%j_%H_%M"`
DGW_CONSOLE_LOG_FILE=$DEPLOY_TMP/dgw_${target}.log

$DEPLOY_ETC/log_roll $DGW_CONSOLE_LOG_FILE 40000 5 

case "$1" in
  start)
	echo "Starting Data Generator Watchdog for ${target}, Log to: ${DGW_CONSOLE_LOG_FILE} "
	$DEPLOY_BIN/dgw start $target 1>> ${DGW_CONSOLE_LOG_FILE} 2>&1 &
	;;
  stop)
	echo "Shutting down Data Generator Watchdog for $target."
	$DEPLOY_BIN/dgw stop $target 1>> ${DGW_CONSOLE_LOG_FILE} 2>&1 
	;;
  restart)
	$0 stop	
	echo "Restarting in 30 secs"
	sleep 30
	$0 start
	;;
  *)
	echo "Usage: $0 {start | stop | restart}"
	exit 1
esac

exit 0
