#!/bin/csh

# -------------------------------------------------------------------
# Script to start the POS_DummyServer to simulate the RCS/PCA Server. 
#-------------------------------------------------------------------

if (${#argv} < 1) then
    echo "\033[45mUsage: dserver <scope> \033[0m"
    exit 1
endif

source ${DEPLOY_BIN}/setup
source ${DEPLOY_BIN}/class_setup
source ${DEPLOY_BIN}/pos_setup

set CONFIG = dummy.properties
set PORT   = 7980

cd $POS_HOME

echo "Starting DummyServer (${1})"

java POS_DummyServer $CONFIG $PORT
   
