#!/bin/csh

#
# --------------------------------------------------------------
# Launcher for: Distributed Transaction Manager Service: (DTMS).
# --------------------------------------------------------------
#

source ${DEPLOY_BIN}/setup
source ${DEPLOY_BIN}/class_setup
source ${DEPLOY_BIN}/dtms_setup

set model = $2

# Add arg list.
source $DTMS_CONFIG/${model}_dtms_args 

echo "Starting DTMS Proxy server (${1})"

set APP = ngat.net.transaction.TransactionManager

java  $APP -name $NAME -id $ID -port $PORT -router -dtms 3 -dtp 5 -routing ${PROXY_CONFIG}/routing_table.properties -start -store $STORE -config ${PROXY_CONFIG}/${model}_dtms.properties

