#!/bin/csh

# ---------------------------------------------------------
# Launcher for: Target of Opportunity Control Relay (TOCR).
# ---------------------------------------------------------

source $DEPLOY_BIN/setup
source $DEPLOY_BIN/class_setup
source $DEPLOY_BIN/gcn_setup

# Add arg list.
source $GCN_CONFIG/gcn_args

set APP = GCN_Server

$JAVA -DTOCR -Dcpdelim=$DD $APP ${DD}id $ID ${DD}port $PORT \
    ${DD}svchost SVC_HOST ${DD}svcport SVC_PORT \
    ${DD}timeout TIMEOUT ${DD}maddr  ${DD}mport

