#!/bin/sh

# ----------------------------------------------
# Startup script for Image Transfer Relay (ITR).
# ----------------------------------------------

. /occ/etc/env

DAT=`date -u +"%j_%H_%M"`
ITR_CONSOLE_LOG_FILE=$DEPLOY_TMP/itr_${DAT}.log

if [ $# -ne 2 ]; then   
    target=$DEPLOY_SYSTEM
else
    target=$2
fi

# Source function library.
/etc/rc.d/init.d/functions

case "$1" in
  start)
	echo "Starting Image Transfer Relay."
	echo "Logging to: " ${ITR_CONSOLE_LOG_FILE}
	$DEPLOY_BIN/itr start $target 1> ${ITR_CONSOLE_LOG_FILE} 2>&1 &
	;;
  stop)
	echo "Shutting down Image Transfer Relay."
	$DEPLOY_BIN/itr stop $target 1> ${ITR_CONSOLE_LOG_FILE} 2>&1 
	;;
  restart)
	$0 stop
	$0 start
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
