#!/bin/csh

# -----------------------------------------
# Launcher for: Image Transfer Relay (ITR).
# -----------------------------------------

if (${#argv} < 1) then
    echo "\033[45mUsage: itr <scope> \033[0m"
    exit 1
endif

source $DEPLOY_BIN/setup
source $DEPLOY_BIN/class_setup
source $DEPLOY_BIN/itr_setup

# Add arg list.
source $ITR_CONFIG/${1}_its_args

# Check certificates here......scripts/check_cert $KEY etc


set APP = ngat.net.SSLFileTransfer

set EGD = -Djava.security.egd=file:/dev/urandom
#set EGD

#set DEBUG = -Djavax.net.debug=all
set DEBUG

$JAVA -DITR -Dcpdelim=${DD} $DEBUG $EGD $APP ${DD}id $ID $SERVER $RELAY $AUTH ${DD}port $PORT ${DD}base $BASE ${DD}key $KEY ${DD}trust $TRUST 
