#!/bin/csh

# ====================================================
# Launcher script for Offline Control Relay (OCR).
# ====================================================

source ${DEPLOY_BIN}/setup
source ${DEPLOY_BIN}/class_setup
source ${DEPLOY_BIN}/ocr_setup

set PID = $DEPLOY_TMP/ocr_${2}.pid

switch ($1)

    case stop:

	echo "Offline Control Relay stopping"
	
	if (! -e $PID) then
	    echo "Cannot locate a PID file: $PID "
	    exit 1
	endif
	set AID = `cat $PID` 
    
	if ($AID == "") then
	    echo "$PID does not contain a valid PID for the IAS"
	    exit 2
	endif

	set BID = `ps -ef | grep $AID | awk '{if ($3 == '$AID') print $2}'`
	echo OCR Watchdog process is $AID ..Killing with SIG_KILL
	kill -9 $AID  
	echo OCR JVM Process is      $BID ..Killing with SIG_KILL
	kill -9 $BID

	breaksw

    case start:

	echo "Offline Control Relay starting"

	echo $$ > $PID
	
	set exit = 0

	$JAVA -DOCR OfflineRelay ${OCR_CONFIG}/${1}_ocr.properties

	echo OCR Process exited with status $exit

	rm -f $PID

	breaksw

endsw
