#!/bin/csh

# ------------------------------------------------------
# Launcher for: Offline Control Relay: OCR client: IAS 
# ------------------------------------------------------

# Usage: ocr_ias <xml-request-file>
#
# 1. xml-request-file: contains the request.
# 2. output is sent to std_err.
#

# Check the request file.
if (${#argv}  < 1) then
    echo "Usage: ocr_ias <xml-request-file>"
    exit 2
endif

if (! -e $1) then
    echo "No such file $1 "
    exit 3
endif

# Common libraries
setenv CLASSPATH
foreach file (ngat/*.jar)
    echo $CLASSPATH | grep $file >& /dev/null
    if ($status != 0) then
	setenv CLASSPATH ${CLASSPATH}:$file
    endif
end

setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:/lib

setenv CLASSPATH ${CLASSPATH}:class

set EGD = -Djava.security.egd=file:/dev/urandom

set KS = -Djavax.net.ssl.keyStore=certs/ukrtoc.private
set KP = -Djavax.net.ssl.keyStorePassword=ukrtocpw
set TS = -Djavax.net.ssl.trustStore=certs/rti_servers.public

set HOST = ltproxy
set PORT = 7920


java -DOCL $EGD $KS $KP $TS OfflineClient @secure @host $HOST @port $PORT \
    @xml-file $1 @console-log-level 3


