#!/bin/csh

# -----------------------------------
# Offline Control Relay (OCR) client.  
# -----------------------------------

# Check the request file.
if (${#argv}  < 1) then
    echo "Usage: ocr_client <xml-request-file>"
    exit 2
endif

if (! -e $1) then
    echo "No such file $1 "
    exit 3
endif

source ${DEPLOY_BIN}/setup
source ${DEPLOY_BIN}/class_setup

$JAVA  OfflineClient @host 150.204.240.118 @port 7920 @xml-file $1 @console-log-level 3


