#!/bin/sh

# ----------------------------------------------
# Startup script for Offline Control Relay (OCR).
# ----------------------------------------------

. /occ/etc/env

DAT=`date -u +"%j_%H_%M"`
OCR_CONSOLE_LOG_FILE=$DEPLOY_TMP/ocr_${DAT}.log

if [ $# -ne 2 ]; then   
    target=$DEPLOY_SYSTEM
else
    target=$2
fi

# Source function library.
/etc/rc.d/init.d/functions

case "$1" in
  start)
	echo "Starting Offline Control Relay."
	echo "Logging to: " ${OCR_CONSOLE_LOG_FILE}
	$DEPLOY_BIN/ocr start $target 1> ${OCR_CONSOLE_LOG_FILE} 2>&1 &
	;;
  stop)
	echo "Shutting down Offline Control Relay."
	$DEPLOY_BIN/ocr stop $target 1> ${OCR_CONSOLE_LOG_FILE} 2>&1 
	;;
  restart)
	$0 stop
	$0 start
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
