#!/bin/csh

# ------------------------------
# Launcher for: PCR GraphClient.
# ------------------------------

source $DEPLOY_BIN/setup
source $DEPLOY_BIN/class_setup
source $DEPLOY_BIN/pcr_setup


if (${#argv} < 2) then
    echo "Usage: pcr_graph <route> <info>"
    echo "       route: Route setup."
    foreach route ($PCR_CONFIG/*_pcrclient_args)
	set rt  = ${route:t}
	echo "             - $rt "
    end
    echo "       info:  Query information."
    foreach info ($PCR_CONFIG/pcrgraph_*_args)
	set it  = ${info:t}
	echo "             - $it "
    end
    exit 1
endif

set model = $1
set rtoc  = $2

source $PCR_CONFIG/${model}_pcrclient_args
source $PCR_CONFIG/pcrgraph_${info}_args

echo "PCR Graph Client startup: ($model) "

cd $PCR_HOME

set DEBUG = 
#set DEBUG = -Djavax.net.debug=all

set EGD = -Djava.security.egd=file:/dev/urandom

set HOST = ftnproxy
set PORT = 7940
set DELAY = 10000

set COMMAND = TELSTATUS
set PARAM = AZIMUTH_ACTUAL
set TITLE = "Azimuth Position"
set UNITS = degs
set LO = 180.0
set HI = 360.0

set KS = "-Djavax.net.ssl.keyStore=${KEYSTORE}"
set KP = "-Djavax.net.ssl.keyStorePassword=${KEYPASS}"
set TS = "-Djavax.net.ssl.trustStore=${TRUSTSTORE}"

$JAVA  $DEBUG $EGD $KEYSTORE $KEYPASS $TRUSTSTORE POSGraphClient -host $HOST -port $PORT -interval $DELAY -command $COMMAND -param $PARAM -title $TITLE -units $UNITS -lo $LO -hi $HI 
