#!/bin/csh

# ====================================================
# Launcher script for Planetarium Control Relay (PCR).
# ====================================================

#source ${DEPLOY_BIN}/setup
#source ${DEPLOY_BIN}/class_setup
#source ${DEPLOY_BIN}/pos_setup

echo "Classpath is: $CLASSPATH "

echo "Starting PCR watchdog (${1})"

set KEYSTORE     = "-Djavax.net.ssl.keyStore=certs/con.private"
set KEYPASS      = "-Djavax.net.ssl.keyStorePassword=geronimo" 
set TRUSTSTORE   = "-Djavax.net.ssl.trustStore=certs/rtoc.public"

set SHUTDOWN = 0
set REBOOT   = 2
set exit     = $REBOOT

set DEBUG = 
#set DEBUG = -Djavax.net.debug=all

#set CONFIG = ${POS_CONFIG}/${1}_pos.properties

set CONFIG = /space/home/dev/src/planetarium/config/lt_pos.properties

#cd $POS_HOME

setenv CLASSPATH ${CLASSPATH}:/space/home/dev/bin/planetarium/java

while ($exit != $SHUTDOWN)
    echo "Starting Planetarium Conrol Relay $1 "
    java $DEBUG $KEYSTORE $KEYPASS $TRUSTSTORE POS_CommandRelay $CONFIG
    set exit = $status
    echo .. POS Process exited with status $exit
end
echo "Shutting down on remote command.."
exit 0
