#!/bin/csh

#
# Script to start a POS_SocketClient.
#

if (${#argv} < 1) then
    echo "Usage: posclient <clientid>"
    echo "          clientId : Name of the client (its keyfile will be '.../clientId.private' )"
    exit 1
endif

source $DEPLOY_BIN/setup
source $DEPLOY_BIN/class_setup
source $DEPLOY_BIN/pcr_setup

cd $POS_HOME

set KEYSTORE   = "-Djavax.net.ssl.keyStore=certs/"${1}".private"
set KEYPASS    = "-Djavax.net.ssl.keyStorePassword="${1}"pw"
set TRUSTSTORE = "-Djavax.net.ssl.trustStore=certs/rti_servers.public"

set EGD = -Djava.security.egd=file:/dev/urandom
#set EGD

set DEBUG = 
#set DEBUG = -Djavax.net.debug=all

set HOST = localhost
set PORT = 8410

java  $DEBUG $EGD $KEYSTORE $KEYPASS $TRUSTSTORE POSSocketClient $HOST $PORT secure

