#!/bin/csh

#
# --------------------
# DTMS Proxy launcher.
# --------------------
#

source ${DEPLOY_BIN}/setup
source ${DEPLOY_BIN}/class_setup
source ${DEPLOY_BIN}/proxy_setup

source ${PROXY_CONFIG}/${1}_args

echo "Classpath is: $CLASSPATH "

echo "Starting DTMS Proxy server (${1})"

set APP = ngat.net.transaction.TransactionManager

java  $APP -name $NAME -id $ID -port $PORT -router -dtms 3 -dtp 5 -routing ${PROXY_CONFIG}/routing_table.properties -start -store $STORE -config ${PROXY_CONFIG}/${1}_proxy.properties

