#!/bin/csh

# ------------------------------------------
# Launcher for: RMI Registry).
# ------------------------------------------

if (${#argv} < 1) then
    echo "Usage: rmi ( start | stop ) "
    exit 1
endif

source /opt/ngat/etc/cshrc

source ${DEPLOY_BIN}/class_setup
source ${DEPLOY_BIN}/rcx_setup
source ${DEPLOY_BIN}/x_setup

echo $CLASSPATH 

set PID = $DEPLOY_TMP/rmi.pid

switch ($1)

    case stop:

	echo "RMI: stopping"
	
	if (! -e $PID) then
	    echo "Cannot locate a PID file: $PID "
	    exit 1
	endif
	set AID = `cat $PID` 
    
	if ($AID == "") then
	    echo "$PID does not contain a valid PID for the RMI"
	    exit 2
	endif

	set BID = `ps -ef | grep $AID | awk '{if ($3 == '$AID') print $2}'`
	echo RMI Watchdog process is $AID ..Killing with SIG_KILL
	kill -9 $AID  
	echo RMI JVM Process is      $BID ..Killing with SIG_KILL
	kill -9 $BID

	rm -f $PID

	breaksw

    case start:

	echo "RMI starting"

	echo $$ > $PID

	set mexit = 0

	$JAVA_HOME/bin/rmiregistry 
#-J-Djava.rmi.server.logCalls=true

	set mexit = $status
	echo "RMI Process exited with status $mexit "

	rm -f $PID

	breaksw

endsw
