#!/bin/csh

source $DEPLOY_BIN/setup
source $DEPLOY_BIN/class_setup
source $DEPLOY_BIN/sfx_setup

# sfx_get <route> <file> <local>

if (${#argv} < 2) then
    echo "Usage: sfx_get <route> <file> <local>"
    echo "       route: Route setup."

    foreach route ($SFX_CONFIG/*_sfxclient_args)
	set rt  = ${route:t}
	echo "             - $rt "
    end
    echo "       file:  File to xfer."
    echo "       local: Relative destination path at client."

    exit 1
endif

set model = $1

source $SFX_CONFIG/${model}_sfxclient_args

echo "SSLFileTransfer Client startup: $model "

# Check we have the key store (server's private key).
if (! -e $KEYSTORE) then   
    echo "Could not find Keystore: $KEYSTORE" 
    exit 1
endif

# Check we have the trust store (clients' public keys).
if (! -e $TRUSTSTORE) then
    echo "Could not find Truststore: $TRUSTSTORE"
    exit 2
endif

set APP = ngat.net.SSLFileTransfer

set EGD = -Djava.security.egd=file:/dev/urandom
#set EGD

#set DEBUG = -Djavax.net.debug=all
set DEBUG

set SSL = TLS

set file = $2
set dest = $3

echo "File: $file Send to: $dest "

set TARGET = "@get $file @local $local"

echo "Target: $TARGET "

$JAVA -Dcpdelim=@ $DEBUG $EGD $APP @client @id $ID $AUTH @key $KEYSTORE @pass $KEYPASS @trust $TRUSTSTORE  \
    @host $RELAY_HOST @port $RELAY_PORT @band 3 $TARGET 
    

