#!/bin/csh

source $DEPLOY_BIN/setup
source $DEPLOY_BIN/class_setup
source $DEPLOY_BIN/sfx_setup

# sfx_show_routes 

echo "SFX Client Routing Models"

foreach route ($SFX_CONFIG/*_sfxclient_args)
	set rt  = ${route:t}
	set rn = `echo $rt | awk -F_ 'BEGIN{x="Route"}{for (i=1;i<NF-1;i++)x=x"_"$i}END{print x}'`
	set rid = `cat $route | grep " ID" | cut -d"=" -f2`
	printf "%b  - $rn \t\t $rid \n"
end

